// Code generated by tools/genmodules; DO NOT EDIT.

package mcpserver

import (
	"github.com/crowdstrike/falcon-mcp/internal/modules/detections"
	hostgroups "github.com/crowdstrike/falcon-mcp/internal/modules/host_groups"
	"github.com/crowdstrike/falcon-mcp/internal/modules/hosts"
	"github.com/crowdstrike/falcon-mcp/internal/modules/registry"
)

// moduleFactories returns every discovered module's factory, ordered by package
// directory name for deterministic module ordering.
func moduleFactories() []registry.Factory {
	return []registry.Factory{
		detections.Factory,
		hostgroups.Factory,
		hosts.Factory,
	}
}
