// Code generated by tools/genmodules; DO NOT EDIT.

package mcpserver

import (
	"github.com/crowdstrike/falcon-mcp/internal/modules/data_protection"
	"github.com/crowdstrike/falcon-mcp/internal/modules/detections"
	"github.com/crowdstrike/falcon-mcp/internal/modules/discover"
	hostgroups "github.com/crowdstrike/falcon-mcp/internal/modules/host_groups"
	"github.com/crowdstrike/falcon-mcp/internal/modules/hosts"
	"github.com/crowdstrike/falcon-mcp/internal/modules/intel"
	"github.com/crowdstrike/falcon-mcp/internal/modules/ioc"
	"github.com/crowdstrike/falcon-mcp/internal/modules/recon"
	"github.com/crowdstrike/falcon-mcp/internal/modules/registry"
	scheduledreports "github.com/crowdstrike/falcon-mcp/internal/modules/scheduled_reports"
	sensorusage "github.com/crowdstrike/falcon-mcp/internal/modules/sensor_usage"
	"github.com/crowdstrike/falcon-mcp/internal/modules/serverless"
	"github.com/crowdstrike/falcon-mcp/internal/modules/spotlight"
)

// moduleFactories returns every discovered module's factory, ordered by package
// directory name for deterministic module ordering.
func moduleFactories() []registry.Factory {
	return []registry.Factory{
		data_protection.Factory,
		detections.Factory,
		discover.Factory,
		hostgroups.Factory,
		hosts.Factory,
		intel.Factory,
		ioc.Factory,
		recon.Factory,
		scheduledreports.Factory,
		sensorusage.Factory,
		serverless.Factory,
		spotlight.Factory,
	}
}
