// MIT License
//
// Copyright (c) 2026 CrowdStrike
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Package registry defines the shared inputs and factory type for tool modules
// and assembles the enabled module set from an explicit factory slice. The
// aggregator (internal/mcpserver, generated by tools/genmodules) supplies that
// slice, so module wiring is explicit rather than hidden in init-time global
// state.
package registry

import (
	"log/slog"
	"time"

	"github.com/crowdstrike/gofalcon/falcon/client"

	"github.com/crowdstrike/falcon-mcp/internal/modules/base"
)

// Deps carries the shared inputs a module factory may need. Each factory pulls
// only the fields its module requires: every module needs API and Logger, while
// Concurrency bounds detail-fetch fan-out for the modules that do bulk lookups.
// The Ngsiem*/Agentworks* durations bound those two modules' poll loops and are
// ignored by every other factory.
type Deps struct {
	API         *client.CrowdStrikeAPISpecification
	Concurrency int
	Logger      *slog.Logger

	NgsiemPollInterval     time.Duration
	NgsiemTimeout          time.Duration
	AgentworksPollInterval time.Duration
	AgentworksTimeout      time.Duration
}

// Factory constructs one module from the shared Deps. Each module exports its
// Factory as a package-level var closing over the module's own wiring (which
// sub-client of Deps.API, whether it uses Concurrency); the generated
// aggregator collects them into the slice passed to Build.
type Factory func(Deps) base.Module

// Build invokes each factory with d and returns the modules in the order the
// factories are given. The aggregator emits them sorted by package name, so the
// result is deterministic without a runtime sort here.
func Build(d Deps, factories []Factory) []base.Module {
	modules := make([]base.Module, 0, len(factories))
	for _, f := range factories {
		modules = append(modules, f(d))
	}
	return modules
}
