name: Markdown Lint

on:
  push:
    branches: [main, go_port]
    paths:
      - '**.md'
  pull_request:
    branches: [main, go_port]
    paths:
      - '**.md'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@4580e1612f6407034edd6c0e4e316d725920867b # v24.2.0
      with:
        config: '.markdownlint.json'
        globs: |
          README.md
          docs/**/*.md
          !docs/changelog.md
          .github/*.md
